openapi: 3.0.0
info:
  title: Week 10
  version: 1.0.0
paths:
  /login:
    post:
      summary: Login User
      requestBody:
        content:
          application/json:
            example:
              username: ayutingting
              password: 1010101010
      responses:
        '200':
          description: Successful response
  /user/register:
    post:
      summary: Register User
      requestBody:
        content:
          application/json:
            example:
              username: taylorswift
              password: 13121989
              role: approver
      responses:
        '200':
          description: Successful response
  /transfer:
    get:
      summary: Get All Transfers
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
  /transfer create:
    post:
      summary: Create Transfer
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            example:
              amount: ""
              currency: ""
              sourceAccount: ""
              destinationAccount: ""
      responses:
        '200':
          description: Successful response
  /:
    patch:
      summary: Approval
      responses:
        '200':
          description: Successful response
  /transfer/{transferId}:
    patch:
      summary: Patch Update
      responses:
        '200':
          description: Successful response
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
